"""
MCP Email Connector - Send decisions, reports, alerts via email
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any, List, Optional
import logging
from datetime import datetime

from app.mcp.base import BaseMCPConnector

logger = logging.getLogger(__name__)


class EmailConnector(BaseMCPConnector):
    """MCP connector for sending emails."""
    
    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
        self.smtp_host = config.get("smtp_host", "smtp.gmail.com")
        self.smtp_port = config.get("smtp_port", 587)
        self.username = config.get("username")
        self.password = config.get("password")
        self.from_email = config.get("from_email")
        self.tls_enabled = config.get("tls_enabled", True)
    
    async def send_decision(self, to_emails: List[str], decision_data: Dict) -> Dict:
        """Send a decision via email."""
        subject = f"Decision Report: {decision_data.get('decision_id', '')}"
        body = self._format_decision(decision_data)
        
        return await self.send_email(to_emails, subject, body, is_html=True)
    
    async def send_alert(self, to_emails: List[str], alert_data: Dict) -> Dict:
        """Send an alert via email."""
        subject = f"🚨 ALERT: {alert_data.get('type', 'Unknown')}"
        body = self._format_alert(alert_data)
        
        return await self.send_email(to_emails, subject, body, is_html=True)
    
    async def send_report(self, to_emails: List[str], report_data: Dict) -> Dict:
        """Send a report via email."""
        subject = f"📊 Report: {report_data.get('title', '')}"
        body = self._format_report(report_data)
        
        return await self.send_email(to_emails, subject, body, is_html=True)
    
    async def send_email(self, to_emails: List[str], subject: str, body: str, is_html: bool = False) -> Dict:
        """Send an email."""
        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = self.from_email
            msg["To"] = ", ".join(to_emails)
            msg["Subject"] = subject
            msg["Date"] = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")
            
            if is_html:
                html_part = MIMEText(body, "html")
                msg.attach(html_part)
            else:
                text_part = MIMEText(body, "plain")
                msg.attach(text_part)
            
            # Connect and send
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.tls_enabled:
                    server.starttls()
                if self.username and self.password:
                    server.login(self.username, self.password)
                server.send_message(msg)
            
            logger.info(f"Email sent to {len(to_emails)} recipients: {', '.join(to_emails)}")
            return {
                "status": "success",
                "message": f"Email sent to {len(to_emails)} recipients",
                "recipients": to_emails
            }
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return {"status": "error", "message": str(e)}
    
    def _format_decision(self, decision: Dict) -> str:
        """Format decision for email."""
        return f"""
        <html>
        <body>
        <h2>📋 Decision Report</h2>
        <table style="border-collapse: collapse;">
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Decision ID:</strong></td>
                <td style="padding: 5px 0;">{decision.get('decision_id', 'N/A')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Step:</strong></td>
                <td style="padding: 5px 0;">{decision.get('step', 'Unknown')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Confidence:</strong></td>
                <td style="padding: 5px 0;">{decision.get('confidence', 0)}%</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Query:</strong></td>
                <td style="padding: 5px 0;">{decision.get('query', 'N/A')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Response:</strong></td>
                <td style="padding: 5px 0;">{decision.get('response', 'N/A')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Timestamp:</strong></td>
                <td style="padding: 5px 0;">{decision.get('timestamp', 'N/A')}</td></tr>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">
            Generated by PersonaVault Decision Operating System
        </p>
        </body>
        </html>
        """
    
    def _format_alert(self, alert: Dict) -> str:
        """Format alert for email."""
        severity_colors = {
            "low": "#fbbf24",
            "medium": "#f97316",
            "high": "#ef4444",
            "critical": "#dc2626"
        }
        color = severity_colors.get(alert.get('severity', 'medium'), '#f97316')
        
        return f"""
        <html>
        <body>
        <h2 style="color: {color};">🚨 ALERT: {alert.get('type', 'Unknown')}</h2>
        <table style="border-collapse: collapse;">
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Severity:</strong></td>
                <td style="padding: 5px 0; color: {color};">{alert.get('severity', 'medium')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Message:</strong></td>
                <td style="padding: 5px 0;">{alert.get('message', '')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Source:</strong></td>
                <td style="padding: 5px 0;">{alert.get('source', 'PersonaVault')}</td></tr>
            <tr><td style="padding: 5px 10px 5px 0;"><strong>Timestamp:</strong></td>
                <td style="padding: 5px 0;">{alert.get('timestamp', 'N/A')}</td></tr>
        </table>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">
            Generated by PersonaVault Decision Operating System
        </p>
        </body>
        </html>
        """
    
    def _format_report(self, report: Dict) -> str:
        """Format report for email."""
        return f"""
        <html>
        <body>
        <h2>📊 Intelligence Report</h2>
        <p><strong>Title:</strong> {report.get('title', '')}</p>
        <p><strong>Description:</strong> {report.get('description', '')}</p>
        <p><strong>Generated:</strong> {report.get('generated_at', 'N/A')}</p>
        <hr>
        <pre style="background: #f3f4f6; padding: 15px; border-radius: 5px; overflow-x: auto;">
        {report.get('content', '')}
        </pre>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">
            Generated by PersonaVault Decision Operating System
        </p>
        </body>
        </html>
        """
