"""clean_start

Revision ID: 097f92621c9c
Revises: 
Create Date: 2026-09-13 14:18:32.828855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '097f92621c9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approver_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_table('behaviour_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('decision_types', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('views', sa.JSON(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('temporal_patterns', sa.JSON(), nullable=True),
    sa.Column('evaluation_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('installed_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_packs_domain'), 'behaviour_packs', ['domain'], unique=False)
    op.create_index(op.f('ix_behaviour_packs_id'), 'behaviour_packs', ['id'], unique=False)
    op.create_index(op.f('ix_behaviour_packs_name'), 'behaviour_packs', ['name'], unique=False)
    op.create_table('bulk_ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('folder_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('successful_files', sa.Integer(), nullable=True),
    sa.Column('failed_files', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_ingestion_jobs_id'), 'bulk_ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_ingestion_jobs_job_id'), 'bulk_ingestion_jobs', ['job_id'], unique=True)
    op.create_table('document_ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('qualified_blocks', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_ingestion_jobs_id'), 'document_ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_document_ingestion_jobs_job_id'), 'document_ingestion_jobs', ['job_id'], unique=True)
    op.create_table('episodic_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('governance_receipt_id', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('hitl_approved', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('consolidated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_entries_governance_receipt_id'), 'episodic_entries', ['governance_receipt_id'], unique=False)
    op.create_index(op.f('ix_episodic_entries_id'), 'episodic_entries', ['id'], unique=False)
    op.create_index(op.f('ix_episodic_entries_user_id'), 'episodic_entries', ['user_id'], unique=False)
    op.create_table('evidence_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('block_metadata', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_qualified', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verifiable_attestation', sa.String(length=255), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_blocks_block_id'), 'evidence_blocks', ['block_id'], unique=True)
    op.create_index(op.f('ix_evidence_blocks_id'), 'evidence_blocks', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('vap_hash', sa.String(), nullable=True),
    sa.Column('action_chain_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_id'), 'pending_actions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_actions_vap_hash'), 'pending_actions', ['vap_hash'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('semantic_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_patterns_id'), 'semantic_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_patterns_pattern_type'), 'semantic_patterns', ['pattern_type'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attestation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_id'), 'simulation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_job_id'), 'simulation_jobs', ['job_id'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sidebar_prefs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('deployment_type', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_settings_id'), 'ai_settings', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pinned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('intelligence_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('trust_level', sa.String(length=20), nullable=False),
    sa.Column('trust_history', sqlite.JSON(), nullable=False),
    sa.Column('contribution_metrics', sqlite.JSON(), nullable=False),
    sa.Column('memory_access', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_contribution', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intelligence_sources_status', 'intelligence_sources', ['status'], unique=False)
    op.create_index('idx_intelligence_sources_trust_score', 'intelligence_sources', ['trust_score'], unique=False)
    op.create_index('idx_intelligence_sources_type', 'intelligence_sources', ['type'], unique=False)
    op.create_index('idx_intelligence_sources_user_id', 'intelligence_sources', ['user_id'], unique=False)
    op.create_table('iot_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_devices_device_id'), 'iot_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_iot_devices_id'), 'iot_devices', ['id'], unique=False)
    op.create_table('legal_matters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('assigned_attorney_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_attorney_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_matters_id'), 'legal_matters', ['id'], unique=False)
    op.create_index(op.f('ix_legal_matters_matter_number'), 'legal_matters', ['matter_number'], unique=True)
    op.create_table('medical_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_alerts_alert_type'), 'medical_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_medical_alerts_device_id'), 'medical_alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_medical_alerts_id'), 'medical_alerts', ['id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_memories_environment_id'), 'memories', ['environment_id'], unique=False)
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_domain'), 'policies', ['domain'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_table('user_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personas_id'), 'user_personas', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('active_persona', sa.String(), nullable=True),
    sa.Column('workspace_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_table('user_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_widgets_id'), 'user_widgets', ['id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_table('behaviour_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('artefact', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('correction', sa.JSON(), nullable=True),
    sa.Column('learned', sa.Boolean(), nullable=True),
    sa.Column('audit_id', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['semantic_patterns.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_events_audit_id'), 'behaviour_events', ['audit_id'], unique=False)
    op.create_index(op.f('ix_behaviour_events_event_type'), 'behaviour_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_behaviour_events_id'), 'behaviour_events', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('trace_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('decision_trajectories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('outcomes', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('success_score', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('corrections', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['semantic_patterns.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_trajectories_id'), 'decision_trajectories', ['id'], unique=False)
    op.create_table('iot_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('linked_memory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_data_data_type'), 'iot_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_iot_data_device_id'), 'iot_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_iot_data_id'), 'iot_data', ['id'], unique=False)
    op.create_index(op.f('ix_iot_data_timestamp'), 'iot_data', ['timestamp'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['legal_matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_table('personal_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('associated_memory_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associated_memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_contexts_context_type'), 'personal_contexts', ['context_type'], unique=False)
    op.create_index(op.f('ix_personal_contexts_id'), 'personal_contexts', ['id'], unique=False)
    op.create_table('decision_evidence_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('audit_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['behaviour_events.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_evidence_links_decision_id'), 'decision_evidence_links', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_links_evidence_id'), 'decision_evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_links_id'), 'decision_evidence_links', ['id'], unique=False)
    op.create_table('decision_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Enum('PERCEPTION', 'POLICY_MATCH', 'AI_RECOMMENDATION', 'ACTION', 'OUTCOME', 'SUMMARY', name='tracestep'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('is_crystallized', sa.Boolean(), nullable=True),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('pack_name', sa.String(), nullable=True),
    sa.Column('pack_version', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_traces_decision_id'), 'decision_traces', ['decision_id'], unique=False)
    op.create_table('provenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('receipt_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provenance_records')
    op.drop_index(op.f('ix_decision_traces_decision_id'), table_name='decision_traces')
    op.drop_table('decision_traces')
    op.drop_index(op.f('ix_decision_evidence_links_id'), table_name='decision_evidence_links')
    op.drop_index(op.f('ix_decision_evidence_links_evidence_id'), table_name='decision_evidence_links')
    op.drop_index(op.f('ix_decision_evidence_links_decision_id'), table_name='decision_evidence_links')
    op.drop_table('decision_evidence_links')
    op.drop_index(op.f('ix_personal_contexts_id'), table_name='personal_contexts')
    op.drop_index(op.f('ix_personal_contexts_context_type'), table_name='personal_contexts')
    op.drop_table('personal_contexts')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_iot_data_timestamp'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_id'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_device_id'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_data_type'), table_name='iot_data')
    op.drop_table('iot_data')
    op.drop_index(op.f('ix_decision_trajectories_id'), table_name='decision_trajectories')
    op.drop_table('decision_trajectories')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_behaviour_events_id'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_event_type'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_audit_id'), table_name='behaviour_events')
    op.drop_table('behaviour_events')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_user_widgets_id'), table_name='user_widgets')
    op.drop_table('user_widgets')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_personas_id'), table_name='user_personas')
    op.drop_table('user_personas')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_domain'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_environment_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_medical_alerts_id'), table_name='medical_alerts')
    op.drop_index(op.f('ix_medical_alerts_device_id'), table_name='medical_alerts')
    op.drop_index(op.f('ix_medical_alerts_alert_type'), table_name='medical_alerts')
    op.drop_table('medical_alerts')
    op.drop_index(op.f('ix_legal_matters_matter_number'), table_name='legal_matters')
    op.drop_index(op.f('ix_legal_matters_id'), table_name='legal_matters')
    op.drop_table('legal_matters')
    op.drop_index(op.f('ix_iot_devices_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_device_id'), table_name='iot_devices')
    op.drop_table('iot_devices')
    op.drop_index('idx_intelligence_sources_user_id', table_name='intelligence_sources')
    op.drop_index('idx_intelligence_sources_type', table_name='intelligence_sources')
    op.drop_index('idx_intelligence_sources_trust_score', table_name='intelligence_sources')
    op.drop_index('idx_intelligence_sources_status', table_name='intelligence_sources')
    op.drop_table('intelligence_sources')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_settings_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_simulation_jobs_job_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_semantic_patterns_pattern_type'), table_name='semantic_patterns')
    op.drop_index(op.f('ix_semantic_patterns_id'), table_name='semantic_patterns')
    op.drop_table('semantic_patterns')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_pending_actions_vap_hash'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_evidence_blocks_id'), table_name='evidence_blocks')
    op.drop_index(op.f('ix_evidence_blocks_block_id'), table_name='evidence_blocks')
    op.drop_table('evidence_blocks')
    op.drop_index(op.f('ix_episodic_entries_user_id'), table_name='episodic_entries')
    op.drop_index(op.f('ix_episodic_entries_id'), table_name='episodic_entries')
    op.drop_index(op.f('ix_episodic_entries_governance_receipt_id'), table_name='episodic_entries')
    op.drop_table('episodic_entries')
    op.drop_index(op.f('ix_document_ingestion_jobs_job_id'), table_name='document_ingestion_jobs')
    op.drop_index(op.f('ix_document_ingestion_jobs_id'), table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index(op.f('ix_bulk_ingestion_jobs_job_id'), table_name='bulk_ingestion_jobs')
    op.drop_index(op.f('ix_bulk_ingestion_jobs_id'), table_name='bulk_ingestion_jobs')
    op.drop_table('bulk_ingestion_jobs')
    op.drop_index(op.f('ix_behaviour_packs_name'), table_name='behaviour_packs')
    op.drop_index(op.f('ix_behaviour_packs_id'), table_name='behaviour_packs')
    op.drop_index(op.f('ix_behaviour_packs_domain'), table_name='behaviour_packs')
    op.drop_table('behaviour_packs')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
