"""add_temporal_patterns_to_behaviour_packs

Revision ID: 5af4c8bb7471
Revises: 0edc92eb1451
Create Date: 2026-08-31 20:11:19.964712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5af4c8bb7471'
down_revision = '0edc92eb1451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodic_entries_governance_receipt_id'), table_name='episodic_entries')
    op.drop_index(op.f('ix_episodic_entries_id'), table_name='episodic_entries')
    op.drop_index(op.f('ix_episodic_entries_user_id'), table_name='episodic_entries')
    op.drop_table('episodic_entries')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_bulk_ingestion_jobs_id'), table_name='bulk_ingestion_jobs')
    op.drop_index(op.f('ix_bulk_ingestion_jobs_job_id'), table_name='bulk_ingestion_jobs')
    op.drop_table('bulk_ingestion_jobs')
    op.drop_index(op.f('ix_user_personas_id'), table_name='user_personas')
    op.drop_table('user_personas')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_transition_snowflake'), table_name='snowflake_transitions')
    op.drop_index(op.f('ix_transition_type'), table_name='snowflake_transitions')
    op.drop_table('snowflake_transitions')
    op.drop_table('controlled_actions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_legal_matters_id'), table_name='legal_matters')
    op.drop_index(op.f('ix_legal_matters_matter_number'), table_name='legal_matters')
    op.drop_table('legal_matters')
    op.drop_table('provenance_records')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_settings_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_patterns_domain'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_is_crystallized'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_phase'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_decision_timelines_event_id'), table_name='decision_timelines')
    op.drop_index(op.f('ix_decision_timelines_id'), table_name='decision_timelines')
    op.drop_table('decision_timelines')
    op.drop_index(op.f('ix_behaviour_packs_domain'), table_name='behaviour_packs')
    op.drop_index(op.f('ix_behaviour_packs_id'), table_name='behaviour_packs')
    op.drop_index(op.f('ix_behaviour_packs_name'), table_name='behaviour_packs')
    op.drop_table('behaviour_packs')
    op.drop_index(op.f('ix_iot_devices_device_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_id'), table_name='iot_devices')
    op.drop_table('iot_devices')
    op.drop_index(op.f('ix_decision_evidence_links_decision_id'), table_name='decision_evidence_links')
    op.drop_index(op.f('ix_decision_evidence_links_evidence_id'), table_name='decision_evidence_links')
    op.drop_index(op.f('ix_decision_evidence_links_id'), table_name='decision_evidence_links')
    op.drop_table('decision_evidence_links')
    op.drop_index(op.f('ix_document_ingestion_jobs_id'), table_name='document_ingestion_jobs')
    op.drop_index(op.f('ix_document_ingestion_jobs_job_id'), table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index(op.f('ix_semantic_patterns_id'), table_name='semantic_patterns')
    op.drop_index(op.f('ix_semantic_patterns_pattern_type'), table_name='semantic_patterns')
    op.drop_table('semantic_patterns')
    op.drop_table('user_connections')
    op.drop_table('users')
    op.drop_index(op.f('ix_policies_domain'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_evidence_blocks_block_id'), table_name='evidence_blocks')
    op.drop_index(op.f('ix_evidence_blocks_id'), table_name='evidence_blocks')
    op.drop_table('evidence_blocks')
    op.drop_index(op.f('ix_behaviour_events_audit_id'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_event_type'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_id'), table_name='behaviour_events')
    op.drop_table('behaviour_events')
    op.drop_index(op.f('ix_medical_alerts_alert_type'), table_name='medical_alerts')
    op.drop_index(op.f('ix_medical_alerts_device_id'), table_name='medical_alerts')
    op.drop_index(op.f('ix_medical_alerts_id'), table_name='medical_alerts')
    op.drop_table('medical_alerts')
    op.drop_index(op.f('ix_iot_data_data_type'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_device_id'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_id'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_timestamp'), table_name='iot_data')
    op.drop_table('iot_data')
    op.drop_index(op.f('ix_simulation_jobs_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_job_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_personal_contexts_context_type'), table_name='personal_contexts')
    op.drop_index(op.f('ix_personal_contexts_id'), table_name='personal_contexts')
    op.drop_table('personal_contexts')
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_pattern_transition_pattern'), table_name='pattern_transitions')
    op.drop_index(op.f('ix_pattern_transition_type'), table_name='pattern_transitions')
    op.drop_table('pattern_transitions')
    op.drop_index(op.f('ix_user_widgets_id'), table_name='user_widgets')
    op.drop_table('user_widgets')
    op.drop_index(op.f('ix_decision_traces_decision_id'), table_name='decision_traces')
    op.drop_table('decision_traces')
    op.drop_index(op.f('ix_decision_trajectories_id'), table_name='decision_trajectories')
    op.drop_table('decision_trajectories')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_pending_actions_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_vap_hash'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('controlled_users')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_snowflakes_domain'), table_name='snowflakes')
    op.drop_index(op.f('ix_snowflakes_parent'), table_name='snowflakes')
    op.drop_table('snowflakes')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('settings', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=1)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('snowflakes',
    sa.Column('id', sa.NUMERIC(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_pattern_id', sa.NUMERIC(), nullable=True),
    sa.Column('parent_pattern_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('focus', sqlite.JSON(), nullable=True),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('actions', sqlite.JSON(), nullable=True),
    sa.Column('patterns', sqlite.JSON(), nullable=True),
    sa.Column('rules', sqlite.JSON(), nullable=True),
    sa.Column('pattern_count', sa.INTEGER(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), nullable=True),
    sa.Column('use_count', sa.INTEGER(), nullable=True),
    sa.Column('pack_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pack_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_crystallized', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snowflakes_parent'), 'snowflakes', ['parent_pattern_id'], unique=False)
    op.create_index(op.f('ix_snowflakes_domain'), 'snowflakes', ['domain'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matter_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['legal_matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_table('controlled_users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('access_level', sa.VARCHAR(length=10), nullable=True),
    sa.Column('supervision_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('supervisor_id', sa.NUMERIC(), nullable=True),
    sa.Column('allowed_domains', sqlite.JSON(), nullable=True),
    sa.Column('max_confidence_threshold', sa.FLOAT(), nullable=True),
    sa.Column('requires_approval', sa.BOOLEAN(), nullable=True),
    sa.Column('allowed_hours_start', sa.INTEGER(), nullable=True),
    sa.Column('allowed_hours_end', sa.INTEGER(), nullable=True),
    sa.Column('allowed_days', sqlite.JSON(), nullable=True),
    sa.Column('compliance_flags', sqlite.JSON(), nullable=True),
    sa.Column('audit_logging', sa.BOOLEAN(), nullable=True),
    sa.Column('daily_decision_limit', sa.INTEGER(), nullable=True),
    sa.Column('monthly_decision_limit', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_configs',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('pinned', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=1)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=True),
    sa.Column('query', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('user_response', sa.TEXT(), nullable=True),
    sa.Column('vap_hash', sa.VARCHAR(), nullable=True),
    sa.Column('action_chain_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_vap_hash'), 'pending_actions', ['vap_hash'], unique=False)
    op.create_index(op.f('ix_pending_actions_id'), 'pending_actions', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('device_model', sa.VARCHAR(length=255), nullable=True),
    sa.Column('device_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('capabilities', sqlite.JSON(), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('trust_level', sa.VARCHAR(length=9), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('public_key', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=500), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_trajectories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('decisions', sqlite.JSON(), nullable=True),
    sa.Column('outcomes', sqlite.JSON(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('pattern_id', sa.INTEGER(), nullable=True),
    sa.Column('policy_id', sa.INTEGER(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('success_score', sa.FLOAT(), nullable=True),
    sa.Column('time_taken', sa.INTEGER(), nullable=True),
    sa.Column('corrections', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['semantic_patterns.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_trajectories_id'), 'decision_trajectories', ['id'], unique=False)
    op.create_table('decision_traces',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('step', sa.VARCHAR(length=17), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_crystallized', sa.BOOLEAN(), nullable=True),
    sa.Column('decision_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('query', sa.VARCHAR(), nullable=True),
    sa.Column('response', sa.VARCHAR(), nullable=True),
    sa.Column('trace', sqlite.JSON(), nullable=True),
    sa.Column('explanation', sa.VARCHAR(), nullable=True),
    sa.Column('pack_name', sa.VARCHAR(), nullable=True),
    sa.Column('pack_version', sa.VARCHAR(), nullable=True),
    sa.Column('latency_ms', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_traces_decision_id'), 'decision_traces', ['decision_id'], unique=False)
    op.create_table('user_widgets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('widget_type', sa.VARCHAR(), nullable=False),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_widgets_id'), 'user_widgets', ['id'], unique=False)
    op.create_table('pattern_transitions',
    sa.Column('id', sa.NUMERIC(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('pattern_id', sa.NUMERIC(), nullable=False),
    sa.Column('transition_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_phase', sa.VARCHAR(length=20), nullable=True),
    sa.Column('to_phase', sa.VARCHAR(length=20), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('transition_metadata', sqlite.JSON(), nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_transition_pattern')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_transition_type'), 'pattern_transitions', ['transition_type'], unique=False)
    op.create_index(op.f('ix_pattern_transition_pattern'), 'pattern_transitions', ['pattern_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.Column('active_persona', sa.VARCHAR(), nullable=True),
    sa.Column('workspace_config', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('query', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('modality', sa.VARCHAR(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('expiry_days', sa.INTEGER(), nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.create_table('personal_contexts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('context_type', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('associated_memory_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['associated_memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_contexts_id'), 'personal_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_personal_contexts_context_type'), 'personal_contexts', ['context_type'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=50), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('result_metrics', sqlite.JSON(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('attestation', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_job_id'), 'simulation_jobs', ['job_id'], unique=1)
    op.create_index(op.f('ix_simulation_jobs_id'), 'simulation_jobs', ['id'], unique=False)
    op.create_table('iot_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('data_type', sa.VARCHAR(), nullable=True),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('linked_memory_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['linked_memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_data_timestamp'), 'iot_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_iot_data_id'), 'iot_data', ['id'], unique=False)
    op.create_index(op.f('ix_iot_data_device_id'), 'iot_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_iot_data_data_type'), 'iot_data', ['data_type'], unique=False)
    op.create_table('medical_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('value', sqlite.JSON(), nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_alerts_id'), 'medical_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_medical_alerts_device_id'), 'medical_alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_medical_alerts_alert_type'), 'medical_alerts', ['alert_type'], unique=False)
    op.create_table('behaviour_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('actor', sa.VARCHAR(), nullable=True),
    sa.Column('artefact', sa.VARCHAR(), nullable=True),
    sa.Column('decision', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('pattern_id', sa.INTEGER(), nullable=True),
    sa.Column('policy_id', sa.INTEGER(), nullable=True),
    sa.Column('correction', sqlite.JSON(), nullable=True),
    sa.Column('learned', sa.BOOLEAN(), nullable=True),
    sa.Column('audit_id', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['semantic_patterns.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_events_id'), 'behaviour_events', ['id'], unique=False)
    op.create_index(op.f('ix_behaviour_events_event_type'), 'behaviour_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_behaviour_events_audit_id'), 'behaviour_events', ['audit_id'], unique=False)
    op.create_table('evidence_blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('block_metadata', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('provenance_score', sa.FLOAT(), nullable=True),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('is_qualified', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DATETIME(), nullable=True),
    sa.Column('verifiable_attestation', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_blocks_id'), 'evidence_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_blocks_block_id'), 'evidence_blocks', ['block_id'], unique=1)
    op.create_table('policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('domain', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('triggers', sqlite.JSON(), nullable=True),
    sa.Column('actions', sqlite.JSON(), nullable=True),
    sa.Column('conditions', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=True),
    sa.Column('failure_count', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_promoted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_domain'), 'policies', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('sidebar_prefs', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_connections',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('connected_user_id', sa.NUMERIC(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_patterns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(), nullable=True),
    sa.Column('trigger', sa.TEXT(), nullable=True),
    sa.Column('correction', sa.TEXT(), nullable=True),
    sa.Column('occurrence_count', sa.INTEGER(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_patterns_pattern_type'), 'semantic_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_semantic_patterns_id'), 'semantic_patterns', ['id'], unique=False)
    op.create_table('document_ingestion_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_blocks', sa.INTEGER(), nullable=True),
    sa.Column('qualified_blocks', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('job_metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_ingestion_jobs_job_id'), 'document_ingestion_jobs', ['job_id'], unique=1)
    op.create_index(op.f('ix_document_ingestion_jobs_id'), 'document_ingestion_jobs', ['id'], unique=False)
    op.create_table('decision_evidence_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('decision_id', sa.INTEGER(), nullable=False),
    sa.Column('evidence_id', sa.INTEGER(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('linked_at', sa.DATETIME(), nullable=True),
    sa.Column('audit_hash', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['behaviour_events.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_evidence_links_id'), 'decision_evidence_links', ['id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_links_evidence_id'), 'decision_evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_links_decision_id'), 'decision_evidence_links', ['decision_id'], unique=False)
    op.create_table('iot_devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('device_name', sa.VARCHAR(), nullable=True),
    sa.Column('device_type', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_devices_id'), 'iot_devices', ['id'], unique=False)
    op.create_index(op.f('ix_iot_devices_device_id'), 'iot_devices', ['device_id'], unique=1)
    op.create_table('behaviour_packs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('domain', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('entities', sqlite.JSON(), nullable=True),
    sa.Column('events', sqlite.JSON(), nullable=True),
    sa.Column('decision_types', sqlite.JSON(), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('prompts', sqlite.JSON(), nullable=True),
    sa.Column('views', sqlite.JSON(), nullable=True),
    sa.Column('policies', sqlite.JSON(), nullable=True),
    sa.Column('evaluation_rules', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('installed_at', sa.DATETIME(), nullable=True),
    sa.Column('installed_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_packs_name'), 'behaviour_packs', ['name'], unique=False)
    op.create_index(op.f('ix_behaviour_packs_id'), 'behaviour_packs', ['id'], unique=False)
    op.create_index(op.f('ix_behaviour_packs_domain'), 'behaviour_packs', ['domain'], unique=False)
    op.create_table('decision_timelines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('step_number', sa.INTEGER(), nullable=True),
    sa.Column('step_type', sa.VARCHAR(), nullable=True),
    sa.Column('step_label', sa.VARCHAR(), nullable=True),
    sa.Column('step_description', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('actor', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['behaviour_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_timelines_id'), 'decision_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_decision_timelines_event_id'), 'decision_timelines', ['event_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('trace_ids', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.NUMERIC(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=True),
    sa.Column('logic', sqlite.JSON(), nullable=True),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('phase', sa.VARCHAR(length=20), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), nullable=True),
    sa.Column('use_count', sa.INTEGER(), nullable=True),
    sa.Column('failure_count', sa.INTEGER(), nullable=True),
    sa.Column('failure_rate', sa.FLOAT(), nullable=True),
    sa.Column('age_days', sa.INTEGER(), nullable=True),
    sa.Column('conflicts', sa.INTEGER(), nullable=True),
    sa.Column('is_crystallized', sa.BOOLEAN(), nullable=True),
    sa.Column('crystallized_at', sa.DATETIME(), nullable=True),
    sa.Column('source_trace_ids', sqlite.JSON(), nullable=True),
    sa.Column('parent_pattern_id', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_pattern_id'], ['patterns.id'], name=op.f('fk_pattern_parent')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_phase'), 'patterns', ['phase'], unique=False)
    op.create_index(op.f('ix_patterns_is_crystallized'), 'patterns', ['is_crystallized'], unique=False)
    op.create_index(op.f('ix_patterns_domain'), 'patterns', ['domain'], unique=False)
    op.create_table('ai_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('profile_name', sa.VARCHAR(), nullable=False),
    sa.Column('provider_type', sa.VARCHAR(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('deployment_type', sa.VARCHAR(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_settings_id'), 'ai_settings', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=1)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('provenance_records',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('trace_id', sa.NUMERIC(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(), nullable=False),
    sa.Column('source_id', sa.VARCHAR(), nullable=False),
    sa.Column('source_text', sa.VARCHAR(), nullable=True),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('receipt_hash', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_matters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matter_number', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_attorney_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_attorney_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_matters_matter_number'), 'legal_matters', ['matter_number'], unique=1)
    op.create_index(op.f('ix_legal_matters_id'), 'legal_matters', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_token', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=1)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('controlled_actions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('request_data', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('approved_by', sa.NUMERIC(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snowflake_transitions',
    sa.Column('id', sa.NUMERIC(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('snowflake_id', sa.NUMERIC(), nullable=False),
    sa.Column('transition_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_phase', sa.VARCHAR(length=20), nullable=True),
    sa.Column('to_phase', sa.VARCHAR(length=20), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['snowflake_id'], ['snowflakes.id'], name=op.f('fk_transition_snowflake')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transition_type'), 'snowflake_transitions', ['transition_type'], unique=False)
    op.create_index(op.f('ix_transition_snowflake'), 'snowflake_transitions', ['snowflake_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('task_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_table('user_personas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('persona_type', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('traits', sqlite.JSON(), nullable=True),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personas_id'), 'user_personas', ['id'], unique=False)
    op.create_table('bulk_ingestion_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('folder_path', sa.VARCHAR(length=512), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_files', sa.INTEGER(), nullable=True),
    sa.Column('successful_files', sa.INTEGER(), nullable=True),
    sa.Column('failed_files', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('job_metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_ingestion_jobs_job_id'), 'bulk_ingestion_jobs', ['job_id'], unique=1)
    op.create_index(op.f('ix_bulk_ingestion_jobs_id'), 'bulk_ingestion_jobs', ['id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(), nullable=True),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('requester_id', sa.INTEGER(), nullable=True),
    sa.Column('approver_ids', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_table('episodic_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('query', sa.TEXT(), nullable=True),
    sa.Column('plan', sqlite.JSON(), nullable=True),
    sa.Column('results', sqlite.JSON(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('evaluation', sqlite.JSON(), nullable=True),
    sa.Column('governance_receipt_id', sa.VARCHAR(), nullable=True),
    sa.Column('signature', sa.VARCHAR(), nullable=True),
    sa.Column('hitl_approved', sa.BOOLEAN(), nullable=True),
    sa.Column('user_feedback', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('consolidated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_entries_user_id'), 'episodic_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_episodic_entries_id'), 'episodic_entries', ['id'], unique=False)
    op.create_index(op.f('ix_episodic_entries_governance_receipt_id'), 'episodic_entries', ['governance_receipt_id'], unique=False)
    # ### end Alembic commands ###
