"""Initial migration with all tables

Revision ID: f3dba9f10158
Revises: 
Create Date: 2026-07-04 15:21:31.809989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dba9f10158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('theme', sa.String(), server_default='light', nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), server_default='Default', nullable=False),
    sa.Column('provider_type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('api_key_enc', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=True),
    sa.Column('max_tokens', sa.Integer(), server_default='100', nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('deployment_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('model_description', sa.String(), nullable=True),
    sa.Column('top_p', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('response_format', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('fallback_model_name', sa.String(), nullable=True),
    sa.Column('fallback_provider_type', sa.String(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('frequency_penalty', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('user_context', sa.String(), nullable=True),
    sa.Column('privacy_level', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('expiry_days', sa.Integer(), server_default='0', nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(), server_default='note', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('associated_files', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expiry_days', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_widgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widgets', sa.String(), server_default='["chat","settings","agent"]', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_widgets')
    op.drop_table('sessions')
    op.drop_table('memories')
    op.drop_table('ai_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
